// Demonym data type.
export interface DemonymEntry {
  code: string // ISO Alpha-2 code (e.g., "ES")
  country: string // Country name (e.g., "Spain")
  demonym: string // Demonym (e.g., "Spanish")
}

// Complete list of countries with their demonyms.
export const demonyms: DemonymEntry[] = [
  { code: "AD", country: "Andorra", demonym: "Andorran" },
  { code: "AE", country: "United Arab Emirates", demonym: "Emirati" },
  { code: "AF", country: "Afghanistan", demonym: "Afghan" },
  { code: "AG", country: "Antigua and Barbuda", demonym: "Antiguan" },
  { code: "AI", country: "Anguilla", demonym: "Anguillian" },
  { code: "AL", country: "Albania", demonym: "Albanian" },
  { code: "AM", country: "Armenia", demonym: "Armenian" },
  { code: "AO", country: "Angola", demonym: "Angolan" },
  { code: "AQ", country: "Antarctica", demonym: "Antarctic" },
  { code: "AR", country: "Argentina", demonym: "Argentine" },
  { code: "AS", country: "American Samoa", demonym: "American Samoan" },
  { code: "AT", country: "Austria", demonym: "Austrian" },
  { code: "AU", country: "Australia", demonym: "Australian" },
  { code: "AW", country: "Aruba", demonym: "Aruban" },
  { code: "AX", country: "Alland Islands", demonym: "Ålandish" },
  { code: "AZ", country: "Azerbaijan", demonym: "Azerbaijani" },
  { code: "BA", country: "Bosnia and Herzegovina", demonym: "Bosnian" },
  { code: "BB", country: "Barbados", demonym: "Barbadian" },
  { code: "BD", country: "Bangladesh", demonym: "Bangladeshi" },
  { code: "BE", country: "Belgium", demonym: "Belgian" },
  { code: "BF", country: "Burkina Faso", demonym: "Burkinabé" },
  { code: "BG", country: "Bulgaria", demonym: "Bulgarian" },
  { code: "BH", country: "Bahrain", demonym: "Bahraini" },
  { code: "BI", country: "Burundi", demonym: "Burundian" },
  { code: "BJ", country: "Benin", demonym: "Beninese" },
  { code: "BL", country: "Saint Barthelemy", demonym: "Barthélemois" },
  { code: "BM", country: "Bermuda", demonym: "Bermudian" },
  { code: "BN", country: "Brunei Darussalam", demonym: "Bruneian" },
  { code: "BO", country: "Bolivia", demonym: "Bolivian" },
  { code: "BR", country: "Brazil", demonym: "Brazilian" },
  { code: "BS", country: "Bahamas", demonym: "Bahamian" },
  { code: "BT", country: "Bhutan", demonym: "Bhutanese" },
  { code: "BV", country: "Bouvet Island", demonym: "Bouvetian" },
  { code: "BW", country: "Botswana", demonym: "Motswana" },
  { code: "BY", country: "Belarus", demonym: "Belarusian" },
  { code: "BZ", country: "Belize", demonym: "Belizean" },
  { code: "CA", country: "Canada", demonym: "Canadian" },
  { code: "CC", country: "Cocos (Keeling) Islands", demonym: "Cocos Islander" },
  { code: "CD", country: "Congo, Democratic Republic of the", demonym: "Congolese" },
  { code: "CF", country: "Central African Republic", demonym: "Central African" },
  { code: "CG", country: "Congo, Republic of the", demonym: "Congolese" },
  { code: "CH", country: "Switzerland", demonym: "Swiss" },
  { code: "CI", country: "Cote d'Ivoire", demonym: "Ivorian" },
  { code: "CK", country: "Cook Islands", demonym: "Cook Islander" },
  { code: "CL", country: "Chile", demonym: "Chilean" },
  { code: "CM", country: "Cameroon", demonym: "Cameroonian" },
  { code: "CN", country: "China", demonym: "Chinese" },
  { code: "CO", country: "Colombia", demonym: "Colombian" },
  { code: "CR", country: "Costa Rica", demonym: "Costa Rican" },
  { code: "CU", country: "Cuba", demonym: "Cuban" },
  { code: "CV", country: "Cape Verde", demonym: "Cape Verdean" },
  { code: "CW", country: "Curacao", demonym: "Curaçaoan" },
  { code: "CX", country: "Christmas Island", demonym: "Christmas Islander" },
  { code: "CY", country: "Cyprus", demonym: "Cypriot" },
  { code: "CZ", country: "Czech Republic", demonym: "Czech" },
  { code: "DE", country: "Germany", demonym: "German" },
  { code: "DJ", country: "Djibouti", demonym: "Djiboutian" },
  { code: "DK", country: "Denmark", demonym: "Danish" },
  { code: "DM", country: "Dominica", demonym: "Dominican" },
  { code: "DO", country: "Dominican Republic", demonym: "Dominican" },
  { code: "DZ", country: "Algeria", demonym: "Algerian" },
  { code: "EC", country: "Ecuador", demonym: "Ecuadorian" },
  { code: "EE", country: "Estonia", demonym: "Estonian" },
  { code: "EG", country: "Egypt", demonym: "Egyptian" },
  { code: "EH", country: "Western Sahara", demonym: "Sahrawi" },
  { code: "ER", country: "Eritrea", demonym: "Eritrean" },
  { code: "ES", country: "Spain", demonym: "Spanish" },
  { code: "ET", country: "Ethiopia", demonym: "Ethiopian" },
  { code: "FI", country: "Finland", demonym: "Finnish" },
  { code: "FJ", country: "Fiji", demonym: "Fijian" },
  { code: "FK", country: "Falkland Islands (Malvinas)", demonym: "Falkland Islander" },
  { code: "FM", country: "Micronesia, Federated States of", demonym: "Micronesian" },
  { code: "FO", country: "Faroe Islands", demonym: "Faroese" },
  { code: "FR", country: "France", demonym: "French" },
  { code: "GA", country: "Gabon", demonym: "Gabonese" },
  { code: "GB", country: "United Kingdom", demonym: "British" },
  { code: "GD", country: "Grenada", demonym: "Grenadian" },
  { code: "GE", country: "Georgia", demonym: "Georgian" },
  { code: "GF", country: "French Guiana", demonym: "French Guianese" },
  { code: "GG", country: "Guernsey", demonym: "Channel Islander" },
  { code: "GH", country: "Ghana", demonym: "Ghanaian" },
  { code: "GI", country: "Gibraltar", demonym: "Gibraltarian" },
  { code: "GL", country: "Greenland", demonym: "Greenlandic" },
  { code: "GM", country: "Gambia", demonym: "Gambian" },
  { code: "GN", country: "Guinea", demonym: "Guinean" },
  { code: "GP", country: "Guadeloupe", demonym: "Guadeloupean" },
  { code: "GQ", country: "Equatorial Guinea", demonym: "Equatoguinean" },
  { code: "GR", country: "Greece", demonym: "Greek" },
  {
    code: "GS",
    country: "South Georgia and the South Sandwich Islands",
    demonym: "South Georgian",
  },
  { code: "GT", country: "Guatemala", demonym: "Guatemalan" },
  { code: "GU", country: "Guam", demonym: "Guamanian" },
  { code: "GW", country: "Guinea-Bissau", demonym: "Bissau-Guinean" },
  { code: "GY", country: "Guyana", demonym: "Guyanese" },
  { code: "HK", country: "Hong Kong", demonym: "Hong Konger" },
  { code: "HM", country: "Heard Island and McDonald Islands", demonym: "Heard Islander" },
  { code: "HN", country: "Honduras", demonym: "Honduran" },
  { code: "HR", country: "Croatia", demonym: "Croatian" },
  { code: "HT", country: "Haiti", demonym: "Haitian" },
  { code: "HU", country: "Hungary", demonym: "Hungarian" },
  { code: "ID", country: "Indonesia", demonym: "Indonesian" },
  { code: "IE", country: "Ireland", demonym: "Irish" },
  { code: "IL", country: "Israel", demonym: "Israeli" },
  { code: "IM", country: "Isle of Man", demonym: "Manx" },
  { code: "IN", country: "India", demonym: "Indian" },
  { code: "IO", country: "British Indian Ocean Territory", demonym: "British" },
  { code: "IQ", country: "Iraq", demonym: "Iraqi" },
  { code: "IR", country: "Iran, Islamic Republic of", demonym: "Iranian" },
  { code: "IS", country: "Iceland", demonym: "Icelandic" },
  { code: "IT", country: "Italy", demonym: "Italian" },
  { code: "JE", country: "Jersey", demonym: "Channel Islander" },
  { code: "JM", country: "Jamaica", demonym: "Jamaican" },
  { code: "JO", country: "Jordan", demonym: "Jordanian" },
  { code: "JP", country: "Japan", demonym: "Japanese" },
  { code: "KE", country: "Kenya", demonym: "Kenyan" },
  { code: "KG", country: "Kyrgyzstan", demonym: "Kyrgyzstani" },
  { code: "KH", country: "Cambodia", demonym: "Cambodian" },
  { code: "KI", country: "Kiribati", demonym: "I-Kiribati" },
  { code: "KM", country: "Comoros", demonym: "Comorian" },
  { code: "KN", country: "Saint Kitts and Nevis", demonym: "Kittitian" },
  { code: "KP", country: "Korea, Democratic People's Republic of", demonym: "North Korean" },
  { code: "KR", country: "Korea, Republic of", demonym: "South Korean" },
  { code: "KW", country: "Kuwait", demonym: "Kuwaiti" },
  { code: "KY", country: "Cayman Islands", demonym: "Caymanian" },
  { code: "KZ", country: "Kazakhstan", demonym: "Kazakhstani" },
  { code: "LA", country: "Lao People's Democratic Republic", demonym: "Laotian" },
  { code: "LB", country: "Lebanon", demonym: "Lebanese" },
  { code: "LC", country: "Saint Lucia", demonym: "Saint Lucian" },
  { code: "LI", country: "Liechtenstein", demonym: "Liechtensteiner" },
  { code: "LK", country: "Sri Lanka", demonym: "Sri Lankan" },
  { code: "LR", country: "Liberia", demonym: "Liberian" },
  { code: "LS", country: "Lesotho", demonym: "Mosotho" },
  { code: "LT", country: "Lithuania", demonym: "Lithuanian" },
  { code: "LU", country: "Luxembourg", demonym: "Luxembourger" },
  { code: "LV", country: "Latvia", demonym: "Latvian" },
  { code: "LY", country: "Libya", demonym: "Libyan" },
  { code: "MA", country: "Morocco", demonym: "Moroccan" },
  { code: "MC", country: "Monaco", demonym: "Monégasque" },
  { code: "MD", country: "Moldova, Republic of", demonym: "Moldovan" },
  { code: "ME", country: "Montenegro", demonym: "Montenegrin" },
  { code: "MF", country: "Saint Martin (French part)", demonym: "Saint-Martinois" },
  { code: "MG", country: "Madagascar", demonym: "Malagasy" },
  { code: "MH", country: "Marshall Islands", demonym: "Marshallese" },
  { code: "MK", country: "Macedonia, the Former Yugoslav Republic of", demonym: "Macedonian" },
  { code: "ML", country: "Mali", demonym: "Malian" },
  { code: "MM", country: "Myanmar", demonym: "Burmese" },
  { code: "MN", country: "Mongolia", demonym: "Mongolian" },
  { code: "MO", country: "Macao", demonym: "Macanese" },
  { code: "MP", country: "Northern Mariana Islands", demonym: "Northern Mariana Islander" },
  { code: "MQ", country: "Martinique", demonym: "Martiniquais" },
  { code: "MR", country: "Mauritania", demonym: "Mauritanian" },
  { code: "MS", country: "Montserrat", demonym: "Montserratian" },
  { code: "MT", country: "Malta", demonym: "Maltese" },
  { code: "MU", country: "Mauritius", demonym: "Mauritian" },
  { code: "MV", country: "Maldives", demonym: "Maldivian" },
  { code: "MW", country: "Malawi", demonym: "Malawian" },
  { code: "MX", country: "Mexico", demonym: "Mexican" },
  { code: "MY", country: "Malaysia", demonym: "Malaysian" },
  { code: "MZ", country: "Mozambique", demonym: "Mozambican" },
  { code: "NA", country: "Namibia", demonym: "Namibian" },
  { code: "NC", country: "New Caledonia", demonym: "New Caledonian" },
  { code: "NE", country: "Niger", demonym: "Nigerien" },
  { code: "NF", country: "Norfolk Island", demonym: "Norfolk Islander" },
  { code: "NG", country: "Nigeria", demonym: "Nigerian" },
  { code: "NI", country: "Nicaragua", demonym: "Nicaraguan" },
  { code: "NL", country: "Netherlands", demonym: "Dutch" },
  { code: "NO", country: "Norway", demonym: "Norwegian" },
  { code: "NP", country: "Nepal", demonym: "Nepali" },
  { code: "NR", country: "Nauru", demonym: "Nauruan" },
  { code: "NU", country: "Niue", demonym: "Niuean" },
  { code: "NZ", country: "New Zealand", demonym: "New Zealander" },
  { code: "OM", country: "Oman", demonym: "Omani" },
  { code: "PA", country: "Panama", demonym: "Panamanian" },
  { code: "PE", country: "Peru", demonym: "Peruvian" },
  { code: "PF", country: "French Polynesia", demonym: "French Polynesian" },
  { code: "PG", country: "Papua New Guinea", demonym: "Papua New Guinean" },
  { code: "PH", country: "Philippines", demonym: "Filipino" },
  { code: "PK", country: "Pakistan", demonym: "Pakistani" },
  { code: "PL", country: "Poland", demonym: "Polish" },
  { code: "PM", country: "Saint Pierre and Miquelon", demonym: "Saint-Pierrais" },
  { code: "PN", country: "Pitcairn", demonym: "Pitcairn Islander" },
  { code: "PR", country: "Puerto Rico", demonym: "Puerto Rican" },
  { code: "PS", country: "Palestine, State of", demonym: "Palestinian" },
  { code: "PT", country: "Portugal", demonym: "Portuguese" },
  { code: "PW", country: "Palau", demonym: "Palauan" },
  { code: "PY", country: "Paraguay", demonym: "Paraguayan" },
  { code: "QA", country: "Qatar", demonym: "Qatari" },
  { code: "RE", country: "Reunion", demonym: "Réunionese" },
  { code: "RO", country: "Romania", demonym: "Romanian" },
  { code: "RS", country: "Serbia", demonym: "Serbian" },
  { code: "RU", country: "Russian Federation", demonym: "Russian" },
  { code: "RW", country: "Rwanda", demonym: "Rwandan" },
  { code: "SA", country: "Saudi Arabia", demonym: "Saudi" },
  { code: "SB", country: "Solomon Islands", demonym: "Solomon Islander" },
  { code: "SC", country: "Seychelles", demonym: "Seychellois" },
  { code: "SD", country: "Sudan", demonym: "Sudanese" },
  { code: "SE", country: "Sweden", demonym: "Swedish" },
  { code: "SG", country: "Singapore", demonym: "Singaporean" },
  { code: "SH", country: "Saint Helena", demonym: "Saint Helenian" },
  { code: "SI", country: "Slovenia", demonym: "Slovenian" },
  { code: "SJ", country: "Svalbard and Jan Mayen", demonym: "Norwegian" },
  { code: "SK", country: "Slovakia", demonym: "Slovak" },
  { code: "SL", country: "Sierra Leone", demonym: "Sierra Leonean" },
  { code: "SM", country: "San Marino", demonym: "Sammarinese" },
  { code: "SN", country: "Senegal", demonym: "Senegalese" },
  { code: "SO", country: "Somalia", demonym: "Somali" },
  { code: "SR", country: "Suriname", demonym: "Surinamese" },
  { code: "SS", country: "South Sudan", demonym: "South Sudanese" },
  { code: "ST", country: "Sao Tome and Principe", demonym: "São Toméan" },
  { code: "SV", country: "El Salvador", demonym: "Salvadoran" },
  { code: "SX", country: "Sint Maarten (Dutch part)", demonym: "Sint Maartener" },
  { code: "SY", country: "Syrian Arab Republic", demonym: "Syrian" },
  { code: "SZ", country: "Swaziland", demonym: "Swazi" },
  { code: "TC", country: "Turks and Caicos Islands", demonym: "Turks and Caicos Islander" },
  { code: "TD", country: "Chad", demonym: "Chadian" },
  { code: "TF", country: "French Southern Territories", demonym: "French" },
  { code: "TG", country: "Togo", demonym: "Togolese" },
  { code: "TH", country: "Thailand", demonym: "Thai" },
  { code: "TJ", country: "Tajikistan", demonym: "Tajikistani" },
  { code: "TK", country: "Tokelau", demonym: "Tokelauan" },
  { code: "TL", country: "Timor-Leste", demonym: "Timorese" },
  { code: "TM", country: "Turkmenistan", demonym: "Turkmen" },
  { code: "TN", country: "Tunisia", demonym: "Tunisian" },
  { code: "TO", country: "Tonga", demonym: "Tongan" },
  { code: "TR", country: "Turkey", demonym: "Turkish" },
  { code: "TT", country: "Trinidad and Tobago", demonym: "Trinidadian" },
  { code: "TV", country: "Tuvalu", demonym: "Tuvaluan" },
  { code: "TW", country: "Taiwan", demonym: "Taiwanese" },
  { code: "TZ", country: "United Republic of Tanzania", demonym: "Tanzanian" },
  { code: "UA", country: "Ukraine", demonym: "Ukrainian" },
  { code: "UG", country: "Uganda", demonym: "Ugandan" },
  { code: "US", country: "United States", demonym: "American" },
  { code: "UY", country: "Uruguay", demonym: "Uruguayan" },
  { code: "UZ", country: "Uzbekistan", demonym: "Uzbekistani" },
  { code: "VA", country: "Holy See (Vatican City State)", demonym: "Vatican" },
  { code: "VC", country: "Saint Vincent and the Grenadines", demonym: "Vincentian" },
  { code: "VE", country: "Venezuela", demonym: "Venezuelan" },
  { code: "VG", country: "British Virgin Islands", demonym: "Virgin Islander" },
  { code: "VI", country: "US Virgin Islands", demonym: "Virgin Islander" },
  { code: "VN", country: "Vietnam", demonym: "Vietnamese" },
  { code: "VU", country: "Vanuatu", demonym: "Ni-Vanuatu" },
  { code: "WF", country: "Wallis and Futuna", demonym: "Wallisian" },
  { code: "WS", country: "Samoa", demonym: "Samoan" },
  { code: "XK", country: "Kosovo", demonym: "Kosovar" },
  { code: "YE", country: "Yemen", demonym: "Yemeni" },
  { code: "YT", country: "Mayotte", demonym: "Mahoran" },
  { code: "ZA", country: "South Africa", demonym: "South African" },
  { code: "ZM", country: "Zambia", demonym: "Zambian" },
  { code: "ZW", country: "Zimbabwe", demonym: "Zimbabwean" },
]

// Get demonym from country name.
// Falls back to returning the original country name if no match found.
export const getDemonym = (country: string | null): string => {
  if (!country) return ""
  const entry = demonyms.find((d) => d.country.toLowerCase() === country.toLowerCase())
  return entry?.demonym ?? country
}

// Waving flag sizes available from flagcdn.com (4:3 aspect ratio).
export type WavingFlagSize =
  | "16x12"
  | "32x24"
  | "48x36"
  | "64x48"
  | "80x60"
  | "96x72"
  | "128x96"
  | "160x120"
  | "192x144"
  | "256x192"

// Get waving flag URL from country name.
// Returns high-quality waving flag image URL or empty string if not found.
export const getFlagUrl = (country: string | null, size: WavingFlagSize = "64x48"): string => {
  if (!country) return ""
  const entry = demonyms.find((d) => d.country.toLowerCase() === country.toLowerCase())
  if (!entry) return ""
  return `https://flagcdn.com/${size}/${entry.code.toLowerCase()}.png`
}
